# Generated by Django 4.2.13 on 2024-06-04 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v1", "0002_event_lecture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecture",
            name="events",
        ),
        migrations.AddField(
            model_name="event",
            name="lecture",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="v1.lecture"
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="students",
            field=models.ManyToManyField(
                related_name="classes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
